### PR TITLE
don't remove proxy events

### PR DESCRIPTION
**Pull request by sibnerian**
I ran into a bug when I called `removeAllListeners` because proxy event listeners (`${UNIQUE}-*} were being nuked! That shouldn't happen, since the whole point is that these events are just passing data through.

### CODE REVIEW

**Comment by sibnerian** [comment]
@jsantell - any chance you want to merge this PR? I think it's still relevant, although it's old.

**Comment by jsantell** [comment]
Hey sorry about that, this looks good to me though -- any chance you have a test for this?

**Comment by sibnerian** [comment]
There can be!

**Comment by sibnerian** [comment]
@jsantell wrote a test for removeAllListeners. I had to modify my strategy a little...seems like listeners were being registered elsewhere in the code as well. Now it just refuses to clobber events whose name begins with the unique string.

**Comment by jsantell** [comment]
Thanks! Published 0.0.3 with these changes

**Comment by sibnerian** [comment]
🎉 !

**Pull request merged**
